apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx2
          image: nginx
